export const SOMALI_OFFICIAL_REGIONS = [
  { name: "Awdal", code: "AWD", capital: "Borama" },
  { name: "Bakool", code: "BKL", capital: "Xuddur" },
  { name: "Banaadir", code: "BND", capital: "Mogadishu" },
  { name: "Bari", code: "BAR", capital: "Bosaso" },
  { name: "Bay", code: "BAY", capital: "Baidoa" },
  { name: "Galguduud", code: "GLG", capital: "Dusmareb" },
  { name: "Gedo", code: "GED", capital: "Garbahaarreey" },
  { name: "Hiiraan", code: "HIR", capital: "Beledweyne" },
  { name: "Jubbada Dhexe", code: "JDX", capital: "Bu'aale" },
  { name: "Jubbada Hoose", code: "JHS", capital: "Kismayo" },
  { name: "Mudug", code: "MDG", capital: "Galkayo" },
  { name: "Nugaal", code: "NGL", capital: "Garowe" },
  { name: "Sanaag", code: "SNG", capital: "Erigavo" },
  { name: "Shabeellaha Dhexe", code: "SDX", capital: "Jowhar" },
  { name: "Shabeellaha Hoose", code: "SHS", capital: "Merca" },
  { name: "Sool", code: "SOL", capital: "Las Anod" },
  { name: "Togdheer", code: "TGD", capital: "Burao" },
  { name: "Woqooyi Galbeed", code: "WQG", capital: "Hargeisa" },
];
